// Production
const FRONT_END_BASE_URL = "https://veiligvertoon.nl";
const API_BASE_URL = "https://api.veiligvertoon.nl";

// Development
// const FRONT_END_BASE_URL = "https://jeroen.eu.ngrok.io";
// const API_BASE_URL = "https://jeroen.eu.ngrok.io";

const VEILIGVERTOON_TRANSLATIONS = {
    "NL": {
        "languageCode": "NL",
        "productDetail-selectSignalword": "Selecteer een signaalwoord",
        "productDetail-selectHStatement": "Selecteer de H- en EUH-gevarenzinnen",
        "productDetail-selectPStatement": "Selecteer de P-zinnen",
        "productDetail-signalWord": "Het signaalwoord ",
        "productDetail-areYouSureTitle": "Weet je het zeker?",
        "productDetail-areYouSureText": "Weet je zeker dat je de geselecteerde zinnen wilt verwijderen?",
        "productDetail-cancel": "Annuleren",
        "productDetail-confirm": "Bevestig",
        "productDetail-noDocumentUploadedError": "Er is geen veiligheidsdocument gevonden, upload eerst een veiligheidsdocument.",
        "productDetail-saveSuccess": "De veiligheidsinformatie is successvol opgeslagen!",
        "productDetail-limitReached": "Je hebt je product limiet bereikt",
        "productDetail-saveError": "Er is een fout opgetreden tijdens het opslaan van de veiligheidsinformatie, probeer het later opnieuw.",
        "productDetail-fillAllFields": "Je moet alle velden invullen!",
        "productDetail-changesRequired": "Wijziging verreist",
        "productDetail-connectionError": "Er kan geen verbinding worden gemaakt met Veiligvertoon, probeer het later opnieuw.",
        "productDetail-fetchingError": "Er is een fout opgetreden tijdens het ophalen van de veiligheidsinformatie, probeer het later opnieuw.",
        "productDetail-ownStatement-1": "Vul hier je eigen",
        "productDetail-ownStatement-2": "zin in",

        "dynamicElementRender-limitReaced": "Je hebt je product limiet bereikt. De veiligheidsinformatie is met een gepauzeerde status opgeslagen. Verhoog je product limiet in je",
        "dynamicElementRender-vvDashboard": "Veiligvertoon dashboard.",
        "dynamicElementRender-title": "Titel",
        "dynamicElementRender-titlePlaceholder": "Naam van het product",
        "dynamicElementRender-titleTooltip": "Vul hier de titel van het product in. Indien een product uit meerdere componenten bestaat vul je hier de titel van het betreffende component in.",
        "dynamicElementRender-statusActive": "Actief",
        "dynamicElementRender-statusPaused": "Gepauzeerd",
        "dynamicElementRender-statusTooltip": "Configureer hier of de veiligheidsinformatie actief op je webshop moet worden getoond of tijdelijk dient te worden gepauzeerd.",
        "dynamicElementRender-msds": "Veiligheidsblad",
        "dynamicElementRender-msds-placeholder": "Upload hier het bij het product behorende veiligheidsinformatieblad als PDF.",
        "dynamicElementRender-placeholder2": "Sleep het bestand hierin of klik om een bestand te selecteren.",
        "dynamicElementRender-tooltip": "Het veiligheidsinformatieblad bevat alle veiligheidsinformatie van het product. Dit document kan worden gebruikt bij het invullen van de benodigde veiligheidsinformatie voor consumenten op je site. Indien je niet beschikt over het veiligheidsblad kun je deze opvragen bij de leverancier of door gaan naar het handmatig invullen.",
        "dynamicElementRender-downloadName": "Bestandsnaam",
        "dynamicElementRender-downloadName-placeholder": "Naam van het bestand",
        "dynamicElementRender-downloadName-tooltip": "Vul hier de bestandsnaam in zoals deze moet worden weergegeven op de website.",
        "dynamicElementRender-downloadCheckbox": "Downloadbaar op website",
        "dynamicElementRender-downloadCheckbox-tooltip": "Geef klanten de mogelijkheid om het veiligheidsblad als PDF te downloaden. Het tot beschikking stellen van het volledige veiligheidsblad wordt gezien als extra aanvulling op de wettelijke eisen, enkel het tot beschikking stellen van het veiligheidsblad is niet voldoende.",
        "dynamicElementRender-scanMsds": "Scan veiligheidsblad",
        "dynamicElementRender-scanMsds-tooltip": "Door het scannen van het veiligheidsblad wordt alle informatie die relevant is voor consumenten automatisch uit het document gehaald en ingevuld.",
        "dynamicElementRender-manualConfigSection": "Handmatig invullen of aanpassen",
        "dynamicElementRender-h-sentences": "H-Zinnen",
        "dynamicElementRender-h-sentences-tootltip": "Selecteer de H- en EUH-gevarenzinnen voor het product. Door de H-zinnen te selecteren worden de GHS-labels, P-zinnen en het signaalwoord automatisch aangevuld. Je vindt de H-zinnen op het etiket van het product of in het veiligheidsblad onder sectie 2.2. De H-zinnen zijn verplicht om de Veiligvertoon veiligheidsinformatie te publiceren op je website.",
        "dynamicElementRender-h-sentences-clearBtn": "Verwijder de geselecteerde H-Zinnen",
        "dynamicElementRender-custom-h-sentences": "Custom H-Zinnen",
        "dynamicElementRender-add-custom-h-sentence": "Voeg custom h-zin toe",
        "dynamicElementRender-GHS-labels": "GHS Labels",
        "dynamicElementRender-GHS-labels-tootltip": "Selecteer h-zinnen, de GHS-labels worden automatisch geselecteerd.",
        "dynamicElementRender-p-sentences": "P-Zinnen",
        "dynamicElementRender-p-sentences-tooltip": "De voorzorgsmaatregelen (P-zinnen) worden automatisch gegenereerd op basis van de gevarenzinnen. Je hebt de mogelijkheid om zelf extra P-zinnen te selecteren of verwijderen. De voorzorgsmaatregelen vind je op het etiket van het product of in het veiligheidsblad onder sectie 2.2.",
        "dynamicElementRender-p-sentences-clearBtn": "Verwijder de geselecteerde P-Zinnen",
        "dynamicElementRender-custom-p-sentences": "Custom P-Zinnen",
        "dynamicElementRender-add-custom-p-sentence": "Voeg custom p-zin toe",
        "dynamicElementRender-signalWord": "Signaalwoord",
        "dynamicElementRender-signalWord-tootltip": "Het signaalwoord wordt automatisch gegenereerd op basis van de gevarenzinnen.",
        "dynamicElementRender-contains": "Bevat",
        "dynamicElementRender-contains-placeholder": "Voer één of meerdere gevaarlijke stoffen in...",
        "dynamicElementRender-contains-tooltip": "Je hebt de mogelijkheid om de gevaarlijke stoffen die het product bevat hier te vermelden. Je vindt deze stoffen op het etiket of in het veiligheidsblad onder sectie 2.2.",
        "dynamicElementRender-extra-info": "Aanvullende informatie",
        "dynamicElementRender-extra-info-placeholder": "Vul optioneel aanvullende informatie in...",
        "dynamicElementRender-extra-info-tooltip": "Je hebt de mogelijkheid om aanvullende opmerkingen te plaatsen voor het product of component. Dit veld komt boven de veiligheidsinformatie te staan.",

        "activation-settings-server-connection-error": "Er kan geen verbinding worden gemaakt met Veiligvertoon, probeer het later opnieuw.",
        "activation-settings-invalid-activation-code-error": "De opgegeven activatiecode is niet geldig. Genereer een nieuwe code in het Veilligvertoon dashboard.",
        "activation-settings-activation-error": "Er is iets fout gegaan tijdens het activeren van je account probeer het later nog een keer.",
        "activation-settings-activation-success": "Je account is successvol gekoppeld!",
        
        "styling-settings-select-font": "Selecteer het font",
        
        "tour-cancel": "Beëindig rondleiding",
        "tour-next": "Volgende stap",
        "tour-step-1A-title": "Welkom bij Veiligvertoon",
        "tour-step-1A-text": "Bedankt voor het downloaden van de Veiligvertoon plugin. Vanaf nu kun je in je Woocomerce productoverzicht gemakkelijk de veiligheidsinformatie van al je producten beheren.",
        "tour-step-1A-cancel": "Geen rondleiding",
        "tour-step-1A-start": "Start rondleiding",
        "tour-step-1B-title": "Bekijk de status van je veiligheidsinformatie",
        "tour-step-1B-text": "Onder deze kolom zie je eenvoudig de status van je veiligheidsinformatie en waneer je deze voor het laatst hebt gewijzigd.",
        "tour-step-1B-text-activeProduct": "Actief product",
        "tour-step-1B-text-pausedProduct": "Gepauzeerd product",
        "tour-step-1B-image-active": "active-information-example",
        "tour-step-1B-image-paused": "paused-information-example",
        "tour-step-1B-cancel": "Beëindig rondleiding",
        "tour-step-1B-next": "Volgende stap",
        "tour-step-1C-title": "Selecteer een product",
        "tour-step-1C-text": "Je beheerd veiligheidsinformatie op productniveau. Open een product om veiligheidsinformatie toe te voegen.",
        "tour-2A-title": "Beheer je veiligheidsinformatie",
        "tour-2A-text": "Onder het kopje 'Veiligvertoon' kun je vanaf nu eenvoudig de veiligheidsinformatie van je producten beheren.",
        "tour-2A-cancel": "Beëindig rondleiding",
        "tour-2A-next": "Volgende stap",
        "tour-2B-title": "Het beheren van je veiligheidsinformatie",
        "tour-2B-text": "In dit overzicht kun je veiligheidsinformatie beheren door het veiligheidsinformatieblad te uploaden of door de informatie handmatig aan te klikken.",
       
        "tour-2C-title": "Het beheren van je veiligheidsinformatie",
        "tour-2C-text": "Je kunt hier het veiligheidsinformatieblad uploaden en scannen om deze te vertalen naar de benodigde informatie voor consumenten.",
        "tour-2D-title": "Het beheren van je veiligheidsinformatie",
        "tour-2D-text": "Je kunt veiligheidsinformatie ook handmatig invullen door gebruik te maken van de volgende velden.",
        "tour-2E-title": "Het beheren van je veiligheidsinformatie",
        "tour-2E-text": "Indien je een product hebt dat bestaat uit meerdere componenten kun je deze hier apart toevoegen.",
        "tour-2F-title": "Het beheren van je veiligheidsinformatie",
        "tour-2F-text": "Publiceer je veiligheidsinformatie door op de knop 'Opslaan' te klikken.",
        "tour-2G-title": "Het stylen van je veiligheidsinformatie",
        "tour-2G-text": "De stijl van de veiligheidsinformatie en waar deze op de productpagina wordt weergegeven beheer je onder het kopje Veiligvertoon van het Wordpress navigatiemenu.",
        "tour-2G-btn-manageStyling": "Beheer styling",
        "tour-3A-title": "Het stylen van je veiligheidsinformatie",
        "tour-3A-text": "Op deze pagina kun je de veiligheidsinformatie volledig naar eigen wens stylen.",
        "tour-3C-title": "Het activeren van je account",
        "tour-3C-text": "Navigeer naar de Veiligvertoon activatie pagina om je account te activeren.",
        "tour-4A-title": "Het activeren van je account",
        "tour-4A-text": "Je hebt op dit moment een demo account waarmee je maximaal één product kunt publiceren. Om meer producten te kunnen publiceren dien je een Veiligvertoon account te koppelen door je activatiecode in te vullen.",
        "tour-4A-text-2": "Je vindt je activatiecode in je persoonlijke",
        "tour-4A-text-3": "Veiligvertoon dashboard",
        "tour-4A-text-4": "onder 'Account > Activatiecode'",
        "tour-4A-text-5": "Nog geen account?",
        "tour-4A-text-6": "Registreer hier.",
        "tour-4A-cancel": "Ik kijk nog even rond",
        "tour-4A-createAccount": "Account aanmaken"
    },
    "EN": {
        "languageCode": "EN",
        "productDetail-selectSignalword": "Select a signal word",
        "productDetail-selectHStatement": "Select the H and EUH hazard statements",
        "productDetail-selectPStatement": "Select the P statements",
        "productDetail-signalWord": "The signal word ",
        "productDetail-areYouSureTitle": "Are you sure?",
        "productDetail-areYouSureText": "Are you sure you want to delete the selected statements?",
        "productDetail-cancel": "Cancel",
        "productDetail-confirm": "Confirm",
        "productDetail-noDocumentUploadedError": "No safety document found, please upload a safety document first.",
        "productDetail-saveSuccess": "The safety information has been successfully saved!",
        "productDetail-limitReached": "You have reached your product limit",
        "productDetail-saveError": "An error occurred while saving the safety information, please try again later.",
        "productDetail-fillAllFields": "You must fill in all fields!",
        "productDetail-changesRequired": "Changes required",
        "productDetail-connectionError": "Unable to connect to Veiligvertoon, please try again later.",
        "productDetail-fetchingError": "An error occurred while fetching the safety information, please try again later.",
        "productDetail-ownStatement-1": "Enter your own",
        "productDetail-ownStatement-2": "sentence here",
    
        "dynamicElementRender-limitReaced": "You have reached your product limit. The safety information is saved with a paused status. Increase your product limit in your",
        "dynamicElementRender-vvDashboard": "Veiligvertoon dashboard.",
        "dynamicElementRender-title": "Title",
        "dynamicElementRender-titlePlaceholder": "Product Name",
        "dynamicElementRender-titleTooltip": "Enter the title of the product here. If a product consists of multiple components, enter the title of the respective component here.",
        "dynamicElementRender-statusActive": "Active",
        "dynamicElementRender-statusPaused": "Paused",
        "dynamicElementRender-statusTooltip": "Configure whether the safety information should be actively displayed on your webshop or temporarily paused.",
        "dynamicElementRender-msds": "Safety Data Sheet",
        "dynamicElementRender-msds-placeholder": "Upload the product's safety data sheet as a PDF here.",
        "dynamicElementRender-placeholder2": "Drag the file here or click to select a file.",
        "dynamicElementRender-tooltip": "The safety data sheet contains all safety information about the product. This document can be used when filling in the required safety information for consumers on your site. If you do not have the safety data sheet, you can request it from the supplier or proceed to manual filling.",
        "dynamicElementRender-downloadName": "File Name",
        "dynamicElementRender-downloadName-placeholder": "File Name",
        "dynamicElementRender-downloadName-tooltip": "Enter the file name as it should appear on the website.",
        "dynamicElementRender-downloadCheckbox": "Downloadable on website",
        "dynamicElementRender-downloadCheckbox-tooltip": "Allow customers to download the safety data sheet as a PDF. Providing the complete safety data sheet is considered an additional supplement to legal requirements; only providing the safety data sheet is not sufficient.",
        "dynamicElementRender-scanMsds": "Scan Safety Data Sheet",
        "dynamicElementRender-scanMsds-tooltip": "Scanning the safety data sheet automatically extracts and fills in all information relevant to consumers from the document.",
        "dynamicElementRender-manualConfigSection": "Manual Entry or Modification",
        "dynamicElementRender-h-sentences": "H Statements",
        "dynamicElementRender-h-sentences-tootltip": "Select the H and EUH hazard statements for the product. By selecting the H statements, the GHS labels, P statements, and the signal word are automatically filled in. You can find the H statements on the product label or in the safety data sheet under section 2.2. H statements are mandatory to publish the Veiligvertoon safety information on your website.",
        "dynamicElementRender-h-sentences-clearBtn": "Remove the selected H statements",
        "dynamicElementRender-custom-h-sentences": "Custom H Statements",
        "dynamicElementRender-add-custom-h-sentence": "Add custom H Sentence",
        "dynamicElementRender-GHS-labels": "GHS Labels",
        "dynamicElementRender-GHS-labels-tootltip": "Select H statements; the GHS labels are automatically selected.",
        "dynamicElementRender-p-sentences": "P Statements",
        "dynamicElementRender-p-sentences-tooltip": "Precautionary measures (P statements) are automatically generated based on the hazard statements. You have the option to select or remove additional P statements. Find precautionary measures on the product label or in the safety data sheet under section 2.2.",
        "dynamicElementRender-p-sentences-clearBtn": "Remove the selected P Statements",
        "dynamicElementRender-custom-p-sentences": "Custom P Statements",
        "dynamicElementRender-add-custom-p-sentence": "Add custom P Sentence",
        "dynamicElementRender-signalWord": "Signal Word",
        "dynamicElementRender-signalWord-tootltip": "The signal word is automatically generated based on the hazard statements.",
        "dynamicElementRender-contains": "Contains",
        "dynamicElementRender-contains-placeholder": "Enter one or more hazardous substances...",
        "dynamicElementRender-contains-tooltip": "You have the option to list the hazardous substances the product contains here. Find these substances on the label or in the safety data sheet under section 2.2.",
        "dynamicElementRender-extra-info": "Additional Information",
        "dynamicElementRender-extra-info-placeholder": "Enter optional additional information...",
        "dynamicElementRender-extra-info-tooltip": "You have the option to add additional comments for the product or component. This field will appear above the safety information.",
    
        "activation-settings-server-connection-error": "Unable to connect to Veiligvertoon, please try again later.",
        "activation-settings-invalid-activation-code-error": "The specified activation code is not valid. Generate a new code in the Veiligvertoon dashboard.",
        "activation-settings-activation-error": "Something went wrong while activating your account, please try again later.",
        "activation-settings-activation-success": "Your account has been successfully linked!",
    
        "styling-settings-select-font": "Select the font",
    
        "tour-cancel": "End tour",
        "tour-next": "Next step",
        "tour-step-1A-title": "Welcome to Veiligvertoon",
        "tour-step-1A-text": "Thank you for downloading the Veiligvertoon plugin. From now on, you can easily manage the safety information of all your products in your Woocommerce product overview.",
        "tour-step-1A-cancel": "Skip tour",
        "tour-step-1A-start": "Start tour",
        "tour-step-1B-title": "View the status of your safety information",
        "tour-step-1B-text": "Under this column, you can easily see the status of your safety information and when you last modified it.",
        "tour-step-1B-text-activeProduct": "Active product",
        "tour-step-1B-text-pausedProduct": "Paused product",
        "tour-step-1B-image-active": "active-information-example-en",
        "tour-step-1B-image-paused": "paused-information-example-en",
        "tour-step-1B-cancel": "End tour",
        "tour-step-1B-next": "Next step",
        "tour-step-1C-title": "Select a product",
        "tour-step-1C-text": "You manage safety information on product level. Edit a product to add safety information.",
        "tour-2A-title": "Manage your safety information",
        "tour-2A-text": "Under the 'Veiligvertoon' section, you can now easily manage the safety information of your products.",
        "tour-2A-cancel": "End tour",
        "tour-2A-next": "Next step",
        "tour-2B-title": "Managing your safety information",
        "tour-2B-text": "In this overview, you can manage safety information by uploading the safety data sheet or by manually selecting the information.",
        "tour-2C-title": "Managing your safety information",
        "tour-2C-text": "You can upload and scan the safety data sheet here to translate it into the required information for consumers.",
        "tour-2D-title": "Managing your safety information",
        "tour-2D-text": "You can also manually enter safety information using the following fields.",
        "tour-2E-title": "Managing your safety information",
        "tour-2E-text": "If you have a product consisting of multiple components, you can add them separately here.",
        "tour-2F-title": "Managing your safety information",
        "tour-2F-text": "Publish your safety information by clicking the 'Save' button.",
        "tour-2G-title": "Styling your safety information",
        "tour-2G-text": "You can manage the style of the safety information and where it appears on the product page under the 'Veiligvertoon' section of the WordPress navigation menu.",
        "tour-2G-btn-manageStyling": "Manage Styling",
        "tour-3A-title": "Styling your safety information",
        "tour-3A-text": "On this page, you can style the safety information according to your preferences.",
        "tour-3C-title": "Activating your account",
        "tour-3C-text": "Navigate to the Veiligvertoon activation page to activate your account.",
        "tour-4A-title": "Activating your account",
        "tour-4A-text": "You currently have a demo account that allows you to publish a maximum of one product. To publish more products, link a Veiligvertoon account by entering your activation code.",
        "tour-4A-text-2": "You can find your activation code in your personal",
        "tour-4A-text-3": "Veiligvertoon dashboard",
        "tour-4A-text-4": "under 'Account > Activation Code'",
        "tour-4A-text-5": "Don't have an account yet?",
        "tour-4A-text-6": "Register here.",
        "tour-4A-cancel": "Start with one product",
        "tour-4A-createAccount": "Create Account"
    }    
}